[platformio]
default_envs = canable_gateway_f072cb

[env:mastervolt_gateway_f042]
platform = ststm32
board = nucleo_f042k6
framework = stm32cube
monitor_speed = 115200
upload_protocol = dfu
build_flags =
  -DMB_USB_VID=0x1A64
  -DMB_USB_PID=0x0000
  -DSTM32F042x6
  -DUSBD_CUSTOMHID_OUTREPORT_BUF_SIZE=64
  -DUSBD_CUSTOM_HID_REPORT_DESC_SIZE=33
  -Iinclude
  -I${platformio.packages_dir}/framework-stm32cubef0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc
  -I${platformio.packages_dir}/framework-stm32cubef0/Middlewares/ST/STM32_USB_Device_Library/Core/Src
  -I${platformio.packages_dir}/framework-stm32cubef0/Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc
  -I${platformio.packages_dir}/framework-stm32cubef0/Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Src
build_src_flags =
  -Wall
  -Wextra
  -Wshadow
  -Wundef
  -Werror=return-type

[env:mastervolt_gateway_f072]
platform = ststm32
board = elektor_f072cb
framework = stm32cube
monitor_speed = 115200
upload_protocol = dfu
build_flags =
  -DMB_USB_VID=0x1A64
  -DMB_USB_PID=0x0000
  -DSTM32F072xB
  -DUSBD_CUSTOMHID_OUTREPORT_BUF_SIZE=64
  -DUSBD_CUSTOM_HID_REPORT_DESC_SIZE=33
  -Iinclude
  -I${platformio.packages_dir}/framework-stm32cubef0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc
  -I${platformio.packages_dir}/framework-stm32cubef0/Middlewares/ST/STM32_USB_Device_Library/Core/Src
  -I${platformio.packages_dir}/framework-stm32cubef0/Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc
  -I${platformio.packages_dir}/framework-stm32cubef0/Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Src
build_src_flags =
  -Wall
  -Wextra
  -Wshadow
  -Wundef
  -Werror=return-type

[env:canable_gateway_f072cb]
platform = ststm32
board = canable_f072cb
framework = stm32cube
monitor_speed = 115200
upload_protocol = dfu
build_flags =
  -DMB_USB_VID=0x1A64
  -DMB_USB_PID=0x0000
  -DSTM32F072xB
  -DUSBD_CUSTOMHID_OUTREPORT_BUF_SIZE=64
  -DUSBD_CUSTOM_HID_REPORT_DESC_SIZE=33
  -Iinclude
  -I${platformio.packages_dir}/framework-stm32cubef0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc
  -I${platformio.packages_dir}/framework-stm32cubef0/Middlewares/ST/STM32_USB_Device_Library/Core/Src
  -I${platformio.packages_dir}/framework-stm32cubef0/Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Inc
  -I${platformio.packages_dir}/framework-stm32cubef0/Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/Src
build_src_flags =
  -Wall
  -Wextra
  -Wshadow
  -Wundef
  -Werror=return-type
